services:
  libbpf-bootstrap:
    build:
      context: .
      dockerfile: dockerfile/libbpf-bootstrap.dockerfile
    image: libbpf-bootstrap
    container_name: libbpf-bootstrap
    privileged: true
    environment:
      PROGRAM_NAME: helloworld
    volumes:
      - ./code:/libbpf-bootstrap/examples/code
      - /sys/kernel/debug/:/sys/kernel/debug/:rw
    entrypoint: ["sh","-c"]
    command:
      - |
        cd /libbpf-bootstrap/examples/code
        rm -rf build/
        sh build.sh $${PROGRAM_NAME}

  code-server:
    build:
      context: .
      dockerfile: dockerfile/code-server.dockerfile
    image: code-server
    container_name: code-server
    privileged: true
    environment:
      PUID: 0
      PASSWORD: ebpf_code-server
      DEFAULT_WORKSPACE: /libbpf-bootstrap/examples/code
    volumes:
      - ./code:/libbpf-bootstrap/examples/code
      - /sys/kernel/debug/:/sys/kernel/debug/:rw
    ports:
      - 8080:8443
    entrypoint: ["sh","-c"]
    command:
      - |
        cd /libbpf-bootstrap/examples/code
        rm -rf build/
        exec /init
