services:
  libbpf-bootstrap:
    build:
      context: .
      dockerfile: libbpf-bootstrap.dockerfile
    image: libbpf-bootstrap
    container_name: libbpf-bootstrap
    privileged: true
    environment:
      PROGRAM_NAME: minimal_legacy
    volumes:
      - ./code/libbpf-bootstrap:/libbpf-bootstrap/examples/code
      - /sys/kernel/debug/:/sys/kernel/debug/:rw
    command:
      - sh
      - -c
      - |
        cd /libbpf-bootstrap/examples/code
        mkdir build
        rm -rf build/*
        cd build
        cmake -DCMAKE_EXE_LINKER_FLAGS="-static" ..
        make $${PROGRAM_NAME}
        timeout 0.5s ./$${PROGRAM_NAME}
        tail -f /dev/null
  
  libbpf-bootstrap_code-server:
    build:
      context: .
      dockerfile: libbpf-bootstrap_code-server.dockerfile
    image: libbpf-bootstrap_code-server
    container_name: libbpf-bootstrap_code-server
    privileged: true
    environment:
      PUID: 0
      PASSWORD: password
      DEFAULT_WORKSPACE: /libbpf-bootstrap/examples/code
    volumes:
      - ./code/libbpf-bootstrap_code-server:/libbpf-bootstrap/examples/code
      - /sys/kernel/debug/:/sys/kernel/debug/:rw
    ports:
      - 8080:8443
    entrypoint: ["sh","-c"]
    command:
      - |
        cd /libbpf-bootstrap/examples/code
        mkdir build
        rm -rf build/*
        cd build
        cmake -DCMAKE_EXE_LINKER_FLAGS="-static" ..
        exec /init
  
  old-libbpf:
    build:
      context: .
      dockerfile: old-libbpf.dockerfile
    image: old-libbpf
    container_name: old-libbpf
    privileged: true
    environment:
      PROGRAM_NAME: helloworld
    volumes:
      - ./code/old-libbpf:/libbpf-bootstrap/examples/code
      - /sys/kernel/debug/:/sys/kernel/debug/:rw
    command:
      - sh
      - -c
      - |
        cd /libbpf-bootstrap/examples/code
        mkdir build
        rm -rf build/*
        cd build
        cmake -DCMAKE_EXE_LINKER_FLAGS="-static" ..
        make $${PROGRAM_NAME}
        timeout 0.5s ./$${PROGRAM_NAME}
        tail -f /dev/null
